### ISSUE TITLE
2.5.1 版本 鸿蒙之眼超频机制修改

### ISSUE THREAD

**Issue by wheatEars** [Taskeren/gtnh-no-nerf#2]
鸿蒙之眼在2.5.1超频效率指数级降低，导致玩家要么堆量物理并行，要么堆发电硬超，已经是2.5.1 UMV阶段数一数二的屎了，希望能就超频和并行机制回滚至2.4.0

**Comment by wheatEars** [comment]
Java知识有限，找不出具体修改的pr了，麻烦作者了XD

**Comment by Taskeren** [comment]
2.5.1才有的改动么

**Comment by wheatEars** [comment]
2.5.1某个meta的改动，应该是

**Comment by wheatEars** [comment]
对的
