### ISSUE TITLE
回滚2.1.2.3之后对GTpp火箭燃料配方的削弱

### ISSUE THREAD

**Issue by Oldmemory1** [Taskeren/gtnh-no-nerf#7]
我直接改的Gtpp的源码，好像就肼，一甲基肼，四氧化二氮这三个配方需要还原。
另外已经被移除的LMP-103S等燃料我没找到相关的配方
相应PR在这
https://github.com/GTNewHorizons/GTplusplus/pull/223/files#diff-3006bbcc25b924a3bec249614183921104c63c1319d7c4d8755bd738fd1ccb94
是这个包下的：gtPlusPlus.core.item.chemistry
这削的压根没法玩，原来产量20%都不到，紫色砍废到不如密集肼了

**Comment by Oldmemory1** [comment]
我自己改了GTpp源码改了之后的RocketFuel.java是这个https://pastebin.com/8116dx2j

**Comment by Taskeren** [comment]
如果只是数值上的削弱的话，感觉只需要按照比例把数字拉大一点就好了。
能不能具体一下哪个配方被硬砍了？

**Comment by Oldmemory1** [comment]
数值上削弱是一甲基肼，四氧化二氮，肼的配方都被砍了，硬砍的我暂时没发现
